name: release

on:
  pull_request:
    types: [closed]
    branches: [release]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
